.zuul.yaml
- [ x] No
changes in zuul yaml
Addition of openshift namespace for build trigger.
=> Add openshift namespace for build trigger

app.py
Database initialization is handled by one component in the whole deployment to
make sure we use correct database schema on updates of components in the
cluster.
=> Do not initialize/update database schema

Pipfile.lock, messages/hash_mismatch.py, messages/message_base.py, messages/missing_package.py, messages/missing_version.py
=> Remove kafka

app.py
https://github.com/thoth-station/storages/issues/1586
=> remove limits on number of python-packages

package_update.py
=> Patch set comprehension

.github/CODEOWNERS, messages/__init__.py
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>
=> Adjust name

openshift/consumer-template.yaml
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>
Correct key name that will cause issue in deployment.
=> Correct key for ConfigMap

openshift/consumer-template.yaml
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>
Add Route and correct port number.
=> Add Route and correct port

openshift/consumer-template.yaml
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>
=> Correct errors

app.sh
faust debugging is high, this gives the option to turn of debug mode
=> add FAUST_DEBUG env option

Pipfile.lock, producer.py
https://github.com/thoth-station/messaging/issues/230
=> update messaging and add component_name and version

producer.py
#149 
#146 
#145 
Instead of propagating exceptions we do nothing
Change return_exceptions flag to true
=> exception won't cause runtime failure

.aicoe-ci.yaml
Related-To: https://github.com/thoth-station/thoth-application/issues/545#issuecomment-735914655
=> set base to v0.20.1

Pipfile, Pipfile.lock, app.sh, producer.py
Update to use messaging > 0.8
Change env variables in `thoth-application` template
No longer using Faust for messaging
=> Messaging v0.8

.github/ISSUE_TEMPLATE/kebechet_info.md, .github/ISSUE_TEMPLATE/kebechet_update.md, Pipfile.lock
fix the typing extension installation issue
include kebechet templates
Related-to: #187
=> fix the typing extension installation issue

producer.py
Removed unused package imports
Related-to: #187
=> Removed unused package imports

.aicoe-ci.yaml
=> use py38 image

.aicoe-ci.yaml, .github/PULL_REQUEST_TEMPLATE.md, .pre-commit-config.yaml, .prow.yaml, .thoth.yaml, producer.py
ci updates w.r.t prow, thoth and aicoe-ci
=> ci updates w.r.t prow, thoth and aicoe-ci

Pipfile.lock, producer.py
if program terminates before messages are sent by librdkafka they will be lost. `flush` will send all pending messages.
=> flush all pending messages

Pipfile, Pipfile.lock
thoth-sourcemanagement isn't used anywhere
=> remove thoth-sourcemanagement from dependencies

Pipfile, Pipfile.lock, producer.py
update to pydantic calling convention for messaging
cc: @KPostOffice
=> update to pydantic calling convention for messaging

.pre-commit-config.yaml, .thoth.yaml, OWNERS, Pipfile.lock
Updated the dependencies and prow config
Fixes: #278
=> :hatched_chick: Updated the dependencies and prow config

producer.py
fixes #291 
See discussion on issue
=> Index no packages
